name: Issue Management with Ubuntu 22.04

on:
  issues:
    types: [opened]  # Trigger when a new issue is created

jobs:
  add-to-project:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 as the runner
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Add the issue to the project board
      - name: Add issue to project
        uses: actions/github-script@v6
        with:
          script: |
            const { data: project } = await github.rest.projects.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              project_id: 1,  # Replace with your project ID
            });

            await github.rest.projects.createCard({
              column_id: 162881453,  # Replace with your column ID
              content_id: context.payload.issue.id,
              content_type: 'Issue',
            });

      # Step 3: Add a label to the issue
      - name: Add label to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage'],  # Replace with your desired label(s)
            });

      # Step 4: Verify OS version (optional)
      - name: Check OS version
        run: lsb_release -a






            
